# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'tableDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tableDemo
pod 'SnapKit', '~> 5.0.1'
pod 'LookinServer', :configurations => ['Debug']

  target 'tableDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tableDemoUITests' do
    # Pods for testing
  end

end




